# Generated by Django 2.2.6 on 2020-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name_jp', models.CharField(default='', max_length=50)),
                ('family_name_jp', models.CharField(default='', max_length=50)),
                ('first_name_en', models.CharField(default='', max_length=50)),
                ('family_name_en', models.CharField(default='', max_length=50)),
                ('fighting_style', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('evaluation', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='初回発行日')),
                ('update_date', models.DateTimeField(verbose_name='最終更新日')),
                ('number_of_preview', models.BigIntegerField(default=0)),
                ('publishing_setting', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuideComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='コメント投稿日')),
                ('comment', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default='False')),
            ],
        ),
    ]
