# Generated by Django 2.2.6 on 2020-03-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecomment',
            name='contributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidecomment',
            name='guide',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Category'),
        ),
        migrations.AddField(
            model_name='guide',
            name='character',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.Character'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='guide',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='guide',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guide.Guide'),
        ),
    ]
