# Generated by Django 2.2.6 on 2020-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20200304_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='full_name_jp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
