# Generated by Django 4.2.4 on 2023-12-31 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_character_full_name_jp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
