# Generated by Django 4.2.4 on 2023-12-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guide_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='publishing_setting',
            field=models.BooleanField(default=True),
        ),
    ]
