# Generated by Django 4.2.4 on 2023-12-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_alter_guide_publishing_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
