# Generated by Django 4.2.4 on 2024-01-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_guide_pub_date_alter_guide_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='初回発行日'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日'),
        ),
    ]
