# Generated by Django 4.2.4 on 2024-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_guide_pub_date_alter_guide_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='update_date',
            field=models.DateTimeField(verbose_name='最終更新日'),
        ),
    ]
