# Generated by Django 4.2.8 on 2024-04-02 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0008_alter_guide_update_date"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE guide_character AUTO_INCREMENT = 33;")
    ]
