# Generated by Django 2.2.6 on 2020-04-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0005_auto_20200304_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitch_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_account',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_channel_url',
            field=models.CharField(default='', max_length=60),
        ),
    ]
