# Generated by Django 4.2.4 on 2023-11-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
