# Generated by Django 4.2.4 on 2024-01-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0008_alter_customuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='更新日')),
                ('log', models.TextField(default='')),
            ],
        ),
    ]
