from django import forms
from .models import Move

class CreateMoveForm(forms.ModelForm):
    class Meta:
        model = Move
        fields = [
        "name_jp",
        "name_jp_ruby",
        "name_en",
        "character",
        "move_type",
        "command_jp",
        "command_en",
        "damage",
        "guard_damage",
        "guard_damage_heat",
        "hit_level",
        "frame_startup",
        "frame_active",
        "frame_recovery",
        "frame_block",
        "frame_hit",
        "frame_counter",
        "frame_crouch_hit",
        "state_player",
        "state_enemy_guard",
        "state_enemy_hit",
        "state_enemy_counter",
        "state_enemy_crouch_hit",
        "state_enemy_air",
        "state_player2",
        "state_enemy_guard2",
        "state_enemy_hit2",
        "state_enemy_counter2",
        "state_enemy_crouch_hit2",
        "state_enemy_air2",
        "state_enemy_downhit2",
        "crouch_status",
        "crouch_status_startup",
        "jump_status",
        "jump_status_startup",
        "power_crash",
        "power_crash_startup",
        "tornado",
        "homing",
        "heat_engager",
        "diminish",
        "is_floor_brake",
        "is_wall_brake",
        "is_throw",
        "throw_tech",
        "throw_tech_frame",
        "state_after_throw_tech_player",
        "state_after_throw_tech_enemy",
        "parent_move",
        "is_combo_guard",
        "is_combo_hit",
        "is_combo_counter",
        "is_combo_crouch_hit",
        "note"
    ]
    widgets={
        'character':forms.HiddenInput(),
    }

class UpdateMoveForm(forms.ModelForm):
    class Meta:
        model = Move
        fields = [
        "name_jp",
        "name_jp_ruby",
        "name_en",
        "character",
        "move_type",
        "command_jp",
        "command_en",
        "damage",
        "guard_damage",
        "guard_damage_heat",
        "hit_level",
        "frame_startup",
        "frame_active",
        "frame_recovery",
        "frame_block",
        "frame_hit",
        "frame_counter",
        "frame_crouch_hit",
        "state_player",
        "state_enemy_guard",
        "state_enemy_hit",
        "state_enemy_counter",
        "state_enemy_crouch_hit",
        "state_enemy_air",
        "state_player2",
        "state_enemy_guard2",
        "state_enemy_hit2",
        "state_enemy_counter2",
        "state_enemy_crouch_hit2",
        "state_enemy_air2",
        "state_enemy_downhit2",
        "crouch_status",
        "crouch_status_startup",
        "jump_status",
        "jump_status_startup",
        "power_crash",
        "power_crash_startup",
        "tornado",
        "homing",
        "heat_engager",
        "diminish",
        "is_floor_brake",
        "is_wall_brake",
        "is_throw",
        "throw_tech",
        "throw_tech_frame",
        "state_after_throw_tech_player",
        "state_after_throw_tech_enemy",
        "parent_move",
        "is_combo_guard",
        "is_combo_hit",
        "is_combo_counter",
        "is_combo_crouch_hit",
        "note"
    ]

        widgets={
        'character':forms.HiddenInput(),
    }

class MoveSortForm(forms.Form):
    move_sort_field = forms.ChoiceField(
        choices = [
                ('command','コマンド順'),
                ('damage_desc','ダメージが高い順'),
                ('damage_asc','ダメージが低い技順'),
                ('frame_startup_asc','発生が早い順'),
                ('frame_startup_desc','発生が遅い順'),
                ('frame_block_desc','ガード硬直差が有利順'),
                ('frame_block_asc','ガード硬直差が不利順'),
                ('frame_hit_desc','ヒット硬直差が有利順'),
                ('frame_hit_asc','ヒット硬直差が不利順'),
                ('frame_counter_desc','カウンター硬直差が有利順'),
                ('frame_counter_asc','カウンター硬直差が不利順'),
                ],

        widget=forms.Select(attrs={'class': 'sort_select_form'}),
        label='並び替え',
        required=False,
   
    )