from django import forms
from .models import Move

class CreateMoveForm(forms.ModelForm):
    class Meta:
        model = Move
        fields = [
        "name_jp",
        "name_jp_ruby",
        "name_en",
        "character",
        "command_jp",
        "command_en",
        "damage",
        "hit_level",
        "frame_startup",
        "frame_active",
        "frame_recovery",
        "frame_block",
        "frame_hit",
        "frame_crouch_hit",
        "frame_counter",
        "state_player",
        "state_enemy_guard",
        "state_enemy_hit",
        "state_enemy_counter",
        "state_enemy_crouch_hit",
        "state_enemy_air",
        "crouch_status",
        "crouch_status_startup",
        "jump_status",
        "jump_status_startup",
        "power_crash",
        "power_crash_startup",
        "tornado",
        "homing",
        "heat_engager",
        "diminish",
        "is_throw",
        "throw_tech",
        "throw_tech_frame",
        "state_after_throw_tech_player",
        "state_after_throw_tech_enemy",
        "parent_move",
        "is_combo_guard",
        "is_combo_hit",
        "is_combo_counter",
        "is_combo_crouch_hit",
        "note"
    ]

class UpdateMoveForm(forms.ModelForm):
    class Meta:
        model = Move
        fields = [
        "name_jp",
        "name_jp_ruby",
        "name_en",
        "character",
        "command_jp",
        "command_en",
        "damage",
        "hit_level",
        "frame_startup",
        "frame_active",
        "frame_recovery",
        "frame_block",
        "frame_hit",
        "frame_crouch_hit",
        "frame_counter",
        "state_player",
        "state_enemy_guard",
        "state_enemy_hit",
        "state_enemy_counter",
        "state_enemy_crouch_hit",
        "state_enemy_air",
        "crouch_status",
        "crouch_status_startup",
        "jump_status",
        "jump_status_startup",
        "power_crash",
        "power_crash_startup",
        "tornado",
        "homing",
        "heat_engager",
        "diminish",
        "is_throw",
        "throw_tech",
        "throw_tech_frame",
        "state_after_throw_tech_player",
        "state_after_throw_tech_enemy",
        "parent_move",
        "is_combo_guard",
        "is_combo_hit",
        "is_combo_counter",
        "is_combo_crouch_hit",
        "note"
    ]

