# Generated by Django 4.2.4 on 2023-12-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0003_character_full_name_jp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrowTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('character', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.character')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_jp', models.CharField(default='', max_length=30)),
                ('name_jp_ruby', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('command_jp', models.CharField(default='', max_length=30)),
                ('command_en', models.CharField(default='', max_length=30)),
                ('damage', models.IntegerField(default=0)),
                ('frame_startup', models.IntegerField(default=0)),
                ('frame_active', models.IntegerField(default=0)),
                ('frame_recovery', models.IntegerField(default=0)),
                ('frame_block', models.IntegerField(default=0)),
                ('frame_hit', models.IntegerField(default=0)),
                ('frame_crouch_hit', models.IntegerField(default=0)),
                ('frame_counter', models.IntegerField(default=0)),
                ('crouch_status', models.BooleanField(default=False)),
                ('crouch_status_startup', models.IntegerField()),
                ('jump_status', models.BooleanField(default=False)),
                ('power_crash', models.BooleanField(default=False)),
                ('power_crash_startup', models.IntegerField(default=0)),
                ('tornado', models.BooleanField(default=False)),
                ('homing', models.BooleanField(default=False)),
                ('heat_engager', models.BooleanField(default=False)),
                ('diminish', models.BooleanField(default=False)),
                ('is_throw', models.BooleanField(default=False)),
                ('throw_tech_frame', models.IntegerField(default=0)),
                ('note', models.TextField()),
                ('parent_move', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.move')),
                ('state_after_throw_tech_enemy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moves_throw_tech_enemy', to='database.state')),
                ('state_after_throw_tech_player', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moves_throw_tech_player', to='database.state')),
                ('state_enemy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy', to='database.state')),
                ('state_enemy_air', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_air', to='database.state')),
                ('state_player', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moves_player', to='database.state')),
                ('throw_tech', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.throwtech')),
            ],
        ),
    ]
