# Generated by Django 4.2.4 on 2023-12-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_character_full_name_jp'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='character',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.character'),
        ),
        migrations.AddField(
            model_name='move',
            name='jump_status_startup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='hit_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.hitlevel'),
        ),
    ]
