# Generated by Django 4.2.4 on 2023-12-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_hitlevel_move_character_move_jump_status_startup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='command_en',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='command_jp',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name_jp_ruby',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='parent_move',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.move'),
        ),
    ]
