# Generated by Django 4.2.4 on 2023-12-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_move_command_en_alter_move_command_jp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='state_enemy',
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_counter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_counter', to='database.state'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_crouch_hit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_crouch_hit', to='database.state'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_guard',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_guard', to='database.state'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_hit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_hit', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='crouch_status_startup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_block',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_crouch_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_recovery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_startup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='jump_status_startup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power_crash_startup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_after_throw_tech_enemy',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_throw_tech_enemy', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_after_throw_tech_player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_throw_tech_player', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_air',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_enemy_air', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves_player', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='throw_tech_frame',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
