# Generated by Django 4.2.4 on 2023-12-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_move_state_enemy_move_state_enemy_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_combo_counter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_combo_crouch_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_combo_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_combo_hit',
            field=models.BooleanField(default=False),
        ),
    ]
