# Generated by Django 4.2.4 on 2023-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_move_is_combo_counter_move_is_combo_crouch_hit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='crouch_status_startup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_crouch_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_recovery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='frame_startup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='jump_status_startup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power_crash_startup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='throw_tech_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
