# Generated by Django 4.2.4 on 2024-01-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_guide_pub_date_alter_guide_update_date'),
        ('database', '0006_alter_move_crouch_status_startup_alter_move_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='character',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.character'),
        ),
        migrations.AlterField(
            model_name='move',
            name='hit_level',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.hitlevel'),
        ),
        migrations.AlterField(
            model_name='move',
            name='parent_move',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.move'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_after_throw_tech_enemy',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_throw_tech_enemy', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_after_throw_tech_player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_throw_tech_player', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_air',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_air', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_counter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_counter', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_crouch_hit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_crouch_hit', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_guard',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_guard', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_enemy_hit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_hit', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state_player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_player', to='database.state'),
        ),
        migrations.AlterField(
            model_name='move',
            name='throw_tech',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.throwtech'),
        ),
        migrations.AlterField(
            model_name='state',
            name='character',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.character'),
        ),
    ]
