# Generated by Django 4.2.4 on 2024-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_move_character_alter_move_hit_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_10ren',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_heat_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_rage_related',
            field=models.BooleanField(default=False),
        ),
    ]
