# Generated by Django 4.2.4 on 2024-01-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_move_is_10ren_move_is_heat_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_basic_move',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_crouch_move',
            field=models.BooleanField(default=False),
        ),
    ]
