# Generated by Django 4.2.4 on 2024-01-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_guide_pub_date_alter_guide_update_date'),
        ('database', '0009_move_is_basic_move_move_is_crouch_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('character', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.character')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='move_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.movetype'),
        ),
    ]
