# Generated by Django 4.2.4 on 2024-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_movetype_move_move_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movetype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
