# Generated by Django 4.2.4 on 2024-01-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_movetype_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
