# Generated by Django 4.2.4 on 2024-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_movetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='guard_damege',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='guard_damege_heat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
