# Generated by Django 4.2.4 on 2024-01-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_move_guard_damege_move_guard_damege_heat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='guard_damege',
            new_name='guard_damage',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='guard_damege_heat',
            new_name='guard_damage_heat',
        ),
    ]
