# Generated by Django 4.2.4 on 2024-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_rename_guard_damege_move_guard_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_floor_brake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_wall_brake',
            field=models.BooleanField(default=False),
        ),
    ]
