# Generated by Django 4.2.4 on 2024-02-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_move_is_floor_brake_move_is_wall_brake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='is_10ren',
        ),
        migrations.RemoveField(
            model_name='move',
            name='is_basic_move',
        ),
        migrations.RemoveField(
            model_name='move',
            name='is_crouch_move',
        ),
        migrations.RemoveField(
            model_name='move',
            name='is_heat_related',
        ),
        migrations.RemoveField(
            model_name='move',
            name='is_rage_related',
        ),
    ]
