# Generated by Django 4.2.4 on 2024-02-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_alter_guide_update_date'),
        ('database', '0016_remove_move_is_10ren_remove_move_is_basic_move_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEnemyAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_display', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateEnemyGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_display', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateEnemyHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_display', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_display', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('character', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.character')),
            ],
        ),
    ]
