# Generated by Django 4.2.4 on 2024-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_stateenemyair_stateenemyguard_stateenemyhit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEnemyDownHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('list_display', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
