# Generated by Django 4.2.4 on 2024-02-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_stateenemydownhit'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='state_enemy_air2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_air2', to='database.stateenemyair'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_counter2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_counter2', to='database.stateenemyhit'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_crouch_hit2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_crouch_hit2', to='database.stateenemyhit'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_downhit2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_downhit2', to='database.stateenemydownhit'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_guard2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_guard2', to='database.stateenemyguard'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_enemy_hit2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_enemy_hit2', to='database.stateenemyhit'),
        ),
        migrations.AddField(
            model_name='move',
            name='state_player2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_player2', to='database.stateplayer'),
        ),
    ]
