# Generated by Django 4.2.4 on 2024-02-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_move_state_enemy_air2_move_state_enemy_counter2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateenemyair',
            name='is_back_quick_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyair',
            name='is_quick_recoverly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyair',
            name='is_side_ukemi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemydownhit',
            name='is_back_quick_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemydownhit',
            name='is_quick_recoverly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemydownhit',
            name='is_side_ukemi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyguard',
            name='is_back_quick_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyguard',
            name='is_blockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyguard',
            name='is_quick_recoverly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyguard',
            name='is_side_ukemi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyhit',
            name='is_back_quick_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyhit',
            name='is_blockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyhit',
            name='is_quick_recoverly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stateenemyhit',
            name='is_side_ukemi',
            field=models.BooleanField(default=False),
        ),
    ]
