# Generated by Django 4.2.4 on 2024-02-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_stateenemyair_is_back_quick_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateenemyhit',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
