# Generated by Django 4.2.4 on 2024-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_stateenemyhit_is_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateenemyair',
            name='list_display',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stateenemydownhit',
            name='list_display',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stateenemyguard',
            name='list_display',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stateenemyhit',
            name='list_display',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stateplayer',
            name='list_display',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
