# Generated by Django 4.2.4 on 2024-02-11 08:15

from django.db import migrations


def update_data(apps, schema_editor):
    Move = apps.get_model('database','Move')
    StatePlayer = apps.get_model('database','StatePlayer')
    StateEnemyGuard = apps.get_model('database','StateEnemyGuard')
    StateEnemyHit = apps.get_model('database','StateEnemyHit')
    StateEnemyAir = apps.get_model('database','StateEnemyAir')

    for obj in Move.objects.all():
        if obj.state_player and obj.state_player.name == "立ち":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="立ち")[0]
        elif obj.state_player and obj.state_player.name == "しゃがみ":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="しゃがみ")[0]
        elif obj.state_player and obj.state_player.name == "背向け":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="背向け")[0]
        elif obj.state_player and obj.state_player.name == "足側仰向けダウン":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="足側仰向けダウン")[0]
        elif obj.state_player and obj.state_player.name == "足側うつ伏せダウン":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="足側うつ伏せダウン")[0]
        elif obj.state_player and obj.state_player.name == "頭側仰向けダウン":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="頭側仰向けダウン")[0]
        elif obj.state_player and obj.state_player.name == "頭側うつ伏せダウン":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="頭側うつ伏せダウン")[0]
        elif obj.state_player and obj.state_player.name == "リベルタドール":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="リベルタドール")[0]
        elif obj.state_player and obj.state_player.name == "パフューマー":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="パフューマー")[0]
        elif obj.state_player and obj.state_player.name == "イアイ・ポズィション":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="イアイ・ポズィション")[0]  
        elif obj.state_player and obj.state_player.name == "運足":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="運足")[0]  
        elif obj.state_player and obj.state_player.name == "旋体":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="旋体")[0]  
        elif obj.state_player and obj.state_player.name == "金剛壁の構え":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="金剛壁の構え")[0]  
        elif obj.state_player and obj.state_player.name == "風足":
            obj.state_player2 = StatePlayer.objects.get_or_create(name="風足")[0]
        


        if obj.state_enemy_guard and obj.state_enemy_guard.name == "立ち":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="立ち")[0]
        elif obj.state_enemy_guard and obj.state_enemy_guard.name == "立ち(ガード可能硬直)":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="立ち(ガード可能硬直)")[0]
        elif obj.state_enemy_guard and obj.state_enemy_guard.name == "しゃがみ":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="しゃがみ")[0]
        elif obj.state_enemy_guard and obj.state_enemy_guard.name == "しゃがみ(ガード可能硬直)":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="しゃがみ(ガード可能硬直)")[0]
        elif obj.state_enemy_guard and obj.state_enemy_guard.name == "ガードブレイク":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="ガードブレイク")[0]
        elif obj.state_enemy_guard and obj.state_enemy_guard.name == "壁よろけ":
            obj.state_enemy_guard2 = StateEnemyGuard.objects.get_or_create(name="壁よろけ")[0]
                                         

        if obj.state_enemy_hit and obj.state_enemy_hit.name == "立ち":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="立ち")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "立ち(ガード可能硬直)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="立ち(ガード可能硬直)")[0]            
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "しゃがみ":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="しゃがみ")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "しゃがみ(ガード可能硬直)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="しゃがみ(ガード可能硬直)")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "足側仰向けダウン":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="通常ダウン")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "足側うつ伏せダウン":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="足側うつ伏せダウン")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "頭側うつ伏せダウン":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="頭側うつ伏せダウン")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "頭側仰向けダウン":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="頭側仰向けダウン")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "吹き飛ばし":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="吹き飛ばし")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "その場吹き飛び":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="その場吹き飛び")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "きりもみ吹き飛び":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="きりもみ吹き飛び")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "後ろ叩きつけダウン":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="後ろ叩きつけダウン")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "鐘楼やられ":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="鐘楼やられ")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "崩れ":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="崩れ")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "腹崩れ":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="腹崩れ")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "尻餅":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="尻餅")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "空中浮かせ(通常)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "空中浮かせ(高)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(高)")[0]
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "空中浮かせ(低)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(低)")[0]       
        elif obj.state_enemy_hit and obj.state_enemy_hit.name == "空中浮かせ(縦回転)":
            obj.state_enemy_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(縦回転)")[0]
                                                                                                                                                
        if obj.state_enemy_counter and obj.state_enemy_counter.name == "立ち":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="立ち")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "立ち(ガード可能硬直)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="立ち(ガード可能硬直)")[0]            
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "しゃがみ":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="しゃがみ")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "しゃがみ(ガード可能硬直)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="しゃがみ(ガード可能硬直)")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "足側仰向けダウン":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="通常ダウン")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "足側うつ伏せダウン":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="足側うつ伏せダウン")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "頭側うつ伏せダウン":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="頭側うつ伏せダウン")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "頭側仰向けダウン":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="頭側仰向けダウン")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "吹き飛ばし":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="吹き飛ばし")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "その場吹き飛び":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="その場吹き飛び")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "きりもみ吹き飛び":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="きりもみ吹き飛び")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "後ろ叩きつけダウン":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="後ろ叩きつけダウン")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "鐘楼やられ":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="鐘楼やられ")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "崩れ":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="崩れ")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "腹崩れ":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="腹崩れ")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "尻餅":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="尻餅")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "空中浮かせ(通常)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="浮かせ")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "空中浮かせ(高)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="浮かせ(高)")[0]
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "空中浮かせ(低)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="浮かせ(低)")[0]       
        elif obj.state_enemy_counter and obj.state_enemy_counter.name == "空中浮かせ(縦回転)":
            obj.state_enemy_counter2 = StateEnemyHit.objects.get_or_create(name="浮かせ(縦回転)")[0]
        
        if obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "立ち":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="立ち")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "立ち(ガード可能硬直)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="立ち(ガード可能硬直)")[0]            
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "しゃがみ":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="しゃがみ")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "しゃがみ(ガード可能硬直)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="しゃがみ(ガード可能硬直)")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "足側仰向けダウン":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="通常ダウン")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "足側うつ伏せダウン":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="足側うつ伏せダウン")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "頭側うつ伏せダウン":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="頭側うつ伏せダウン")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "頭側仰向けダウン":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="頭側仰向けダウン")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "吹き飛ばし":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="吹き飛ばし")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "その場吹き飛び":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="その場吹き飛び")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "きりもみ吹き飛び":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="きりもみ吹き飛び")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "後ろ叩きつけダウン":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="後ろ叩きつけダウン")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "鐘楼やられ":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="鐘楼やられ")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "崩れ":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="崩れ")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "腹崩れ":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="腹崩れ")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "尻餅":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="尻餅")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "空中浮かせ(通常)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "空中浮かせ(高)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(高)")[0]
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "空中浮かせ(低)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(低)")[0]       
        elif obj.state_enemy_crouch_hit and obj.state_enemy_crouch_hit.name == "空中浮かせ(縦回転)":
            obj.state_enemy_crouch_hit2 = StateEnemyHit.objects.get_or_create(name="浮かせ(縦回転)")[0]
    
        if obj.state_enemy_air and obj.state_enemy_air.name == "空中":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="空中ヒット")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中吹き飛び":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="空中吹き飛び")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中きりもみ":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="きりもみ")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中きりもみ(高)":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="きりもみ")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中きりもみ吹き飛び":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="きりもみ吹き飛び")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中縦回転":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="縦回転")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "空中裏返り":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="裏返り")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "叩きつけ":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="叩きつけ")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "叩きつけ(後転可能)":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="叩きつけ(後転可能)")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "吹き飛ばし":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="吹き飛ばし")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "トルネード":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="トルネード")[0]
        elif obj.state_enemy_air and obj.state_enemy_air.name == "ヒートバースト叩きつけ":
            obj.state_enemy_air2 = StateEnemyAir.objects.get_or_create(name="ヒートバースト叩きつけ")[0]
        
        obj.save()
                               

        
    
            
        
class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_stateenemyair_list_display_and_more'),
    ]

    operations = [
        migrations.RunPython(update_data),
    ]
