"""
Django settings for tekkenSite project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%(kw=*vae_kso9)y#0s66=#ly*&ebb+-#)1c6%!pj_db10-c(b'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'video.apps.VideoConfig',#動画用
    'stream.apps.StreamConfig',#配信用
    'database.apps.DatabaseConfig',#データベース用
    'top.apps.TopConfig',#トップ用
    'guide.apps.GuideConfig',  # ガイド用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'sslserver',
    'ckeditor',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# cookie
# settings.py


# ルートディレクトリ
ROOT_URLCONF = 'tekkenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tekkenSite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

if DEBUG == True :
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'tekkensite',
            'USER': 'taichi84',
            'PASSWORD': 'kaiketsu84',
            'HOST': '192.168.0.6',
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else :
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'tekkensite',
            'USER': 'taichi84',
            'PASSWORD': 'kaiketsu84',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }



AUTH_USER_MODEL = "top.CustomUser"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# 認証バックエンドを指定する（カスタムバックエンドを使用する場合、追加する）
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # デフォルトのバックエンド
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    BASE_DIR
]
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Email設定用
# DEFAULT_FROM_EMAIL = 'tekkenmaniax0401@gmail.com'

if os.name == 'nt':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'tekkenmaniax0401@gmail.com'
EMAIL_HOST_PASSWORD = 'lhgwvznitfsktrii'
EMAIL_USE_TLS = True

# cookie関連
if os.name == 'nt':
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_HOST = 'testaichi'  # 自己署名証明書で使用するドメインを指定
    SECURE_SSL_CERT = '/home/taichi84/dev/tekkensite/server.crt'  # 証明書ファイルへのパスを指定
    SECURE_SSL_KEY = '/home/taichi84/dev/tekkensite/server.key' # 秘密鍵ファイルへのパスを指定

# CERTBOT用の変数追記
CERT_ROOT = os.path.join(BASE_DIR, '.well-known')
CERT_URL = '/.well-known/'


# Redisキャッシュの設定
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',  # Redisサーバーのアドレス
        'OPTIONS': {
           # 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Redisセッションストアの設定
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

#CKeditorの設定
if DEBUG == True :
    EMBED_PROVIDER ="https://localhost:8000/guide/embed_api?url={url}&callback={callback}"
else:
    EMBED_PROVIDER ="https://extreme-gamers.info/guide/embed_api?url={url}&callback={callback}"

#IFRAMELY_API_KEY = "14ce4ab66a1762fd0a61c2"
IFRAMELY_API_KEY = "c7df83dde9a0f7d49161a2"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Link', 'Unlink'],
            ['Table', 'HorizontalRule', 'SpecialChar'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Embed'],
            ['Source'],
            ['RemoveFormat', 'Maximize'],
            ['CreatePlaceholder', 'ImageCaption', 'ImageToolbar', 'ImageStyle', 'ImageDimensions', 'ImageAlign'],
          
        ],
        'width': 1200,
        'height':800,
        'extraPlugins': ','.join([
            'autoembed',
            'embedsemantic', 
            'embedbase',
            'embed',
        ]),
        'embed_provider':EMBED_PROVIDER,
        #'embed_provider':'//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}&maxwidth=800&maxheight=350&api_key=' + IFRAMELY_API_KEY,
        'contentsCss':['/static/guide/css/ckeditor.css'],
 
          
    },
}
# CORS設定


#LoginRequiredMixinの設定

LOGIN_URL = 'login'