# Generated by Django 4.2.4 on 2023-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(default='', max_length=50)),
                ('channel_title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('viewcount', models.IntegerField(default=0)),
                ('subscribercount', models.IntegerField(default=0)),
                ('videocount', models.IntegerField(default=0)),
                ('thumbnails_default', models.CharField(default='', max_length=255)),
                ('thumbnails_medium', models.CharField(default='', max_length=255)),
                ('thumbnails_high', models.CharField(default='', max_length=255)),
                ('live_broadcast_content', models.CharField(default='', max_length=100)),
                ('publish_time', models.DateTimeField(verbose_name='チャンネル設立日')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('video_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('thumbnails_high', models.TextField(max_length=255)),
                ('thumbnails_medium', models.TextField(max_length=255)),
                ('thumbnails_default', models.TextField(max_length=255)),
                ('channel_title', models.CharField(default='', max_length=100)),
                ('playlist_id', models.CharField(default='', max_length=100)),
                ('video_owner_channel_title', models.CharField(default='', max_length=100)),
                ('video_owner_channel_id', models.CharField(default='', max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
    ]
