# Generated by Django 4.2.4 on 2023-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(default='1990-01-01', verbose_name='動画投稿日'),
        ),
    ]
