# Generated by Django 4.2.4 on 2023-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_tag_channel_tags_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='update_playlist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
