# Generated by Django 4.2.4 on 2023-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_channel_update_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_broadcasting',
            field=models.BooleanField(default=False, help_text='配信中ならTrue'),
        ),
        migrations.AddField(
            model_name='channel',
            name='latest_video_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
