# Generated by Django 4.2.4 on 2024-01-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0005_channel_is_broadcasting_channel_latest_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('channel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.channel')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
